# Import lIbraries

In [2]:
import pandas as pd
import numpy as np
import re
import nltk
import joblib

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

# Load Fake Dataset

In [4]:
fake_df = pd.read_excel(
    r"C:\Users\Admin\Downloads\PolyglotFakeFacts A multilingual dataset of fake a\Fake.xlsx"
)

print("Fake Dataset Shape:", fake_df.shape)
fake_df.head()

Fake Dataset Shape: (4912, 10)

,Gathering date,News date,Language,URL,Domain,Keywords,News headline,News original text,English translated version,Label
0,2023-05-30,2019-10-22,arabic,https://arabic.sputniknews.com/russia/20191022...,arabic.sputniknews.com,Crimea,"موسكو تكشف عن وجود مشروع سياسي للغرب في دولة ""...",كشف المتحدث باسم الرئاسة الروسية دميتري بيسكوف...,Russian presidential spokesman Dmitry Peskov r...,fake
1,2023-05-30,2019-07-18,arabic,https://arabic.rt.com/middle_east/1032932-%D8%...,arabic.rt.com,"Idlib, Syrian War",أوكرانيا: مستعدون للحوار مع روسيا حول القرم,أحمــــــــــــــــــــد عمرخالـــــــــــــــ...,Ahmed Omar Khaled NajehUkrainian Foreign Minis...,fake
2,2023-05-30,2019-11-27,arabic,https://arabic.sputniknews.com/russia/20191127...,sptnkne.ws,North Africa,مرصد الزلازل الأردني: المنطقة تشهد هزات أرضية ...,مرصد الزلازل الأردنيقال مدير مرصد الزلازل الأر...,"The Jordanian Seismological Observatory, Ghass...",fake
3,2023-05-30,2020-06-01,arabic,https://arabic.rt.com/world/1119959-%D8%A7%D9%...,arabic.rt.com,"Diplomacy with Russia, Anti-Russian, Elections",العقوبات ضد روسيا أبدية ويجب على موسكو التصرف ...,أحمــــــــــــــــــــد عمرخالـــــــــــــــ...,Ahmed Omar Khaled NajehThe Russian Deputy Fore...,fake
4,2023-05-30,2020-04-11,arabic,https://russiarab.com/archives/39296/,Russia in Arabic,"EU budget, coronavirus, EU disintegration","الكرملين: اتهامات التشيك لروسيا ""مشينة """,أحمــــــــــــــــــــد عمرخالـــــــــــــــ...,Ahmed Omar Khaled Nageh The Russian presidenti...,fake

# Load Real Dataset

In [6]:
real_df = pd.read_excel(
    r"C:\Users\Admin\Downloads\PolyglotFakeFacts A multilingual dataset of fake a\Real.xlsx"
)

print("Real Dataset Shape:", real_df.shape)
real_df.head()

Real Dataset Shape: (5294, 10)

,gathering date,news date,url,domain,language,keywords,news headline,news original text,english translated version,label
0,2023-06-08 16:35:39.788000,NaN,https://www.dnes.bg/izbori-2023/2023/06/07/iav...,www.dnes.bg,Bulgarian,"politics, academician, nikolay, voted",Явор Божанков: Вчера ни атакуваха брутално,С абсолютна убеденост гласувах за наш кабинет ...,"With absolute conviction, I voted for our cabi...",real
1,2023-06-08 16:05:45.672000,NaN,https://www.dnes.bg/politika/2023/06/08/shte-s...,www.dnes.bg,Bulgarian,"politics, yavor, bozhankov, twice","Ще спрат ли скандалите в НС? 'Възраждане'"" дад...","След като вчера на два пъти депутатите от ''""В...","After twice yesterday the MPs from ""Vazrazhdan...",real
2,2023-06-08 16:47:54.618000,NaN,https://www.dnes.bg/mish-mash/2023/06/04/short...,www.dnes.bg,Bulgarian,"sports, summer, garden, close",Шорти от деним - неизменна част от летния гард...,"Лятото е толкова близо, че на практика можем д...",Summer is so close we can practically taste it...,real
3,2023-06-08 16:06:00.282000,NaN,https://www.dnes.bg/temida/2023/06/08/shestima...,www.dnes.bg,Bulgarian,"legal, geshev's, ognyan, officers",Шестимата от ВСС оттеглиха искането за оставка...,Заседанието на ВСС за оставка на Гешев се прео...,The session of the SJC for Geshev's resignatio...,real
4,2023-06-08 16:53:25.269000,NaN,https://www.dnes.bg/akoshtete-vqrvaite/2020/08...,www.dnes.bg,Bulgarian,"politics, sunny, beach, party",Шампанско и... ковчег! Кръст и монахини на пар...,Парти на плаж в Слънчев бряг предизвика стотиц...,A beach party in Sunny Beach caused hundreds o...,real

# Create Target Labels

In [8]:
fake_df["target"] = 1
real_df["target"] = 0

print(fake_df["target"].value_counts())
print(real_df["target"].value_counts())

target
1    4912
Name: count, dtype: int64
target
0    5294
Name: count, dtype: int64

# Rename Text Columns

In [10]:
fake_df = fake_df.rename(
    columns={"English translated version": "text"}
)

real_df = real_df.rename(
    columns={"english translated version": "text"}
)

# Keep Required Columns

In [12]:
fake_df = fake_df[["text", "target"]]
real_df = real_df[["text", "target"]]

# Combine Datasets

In [14]:
df = pd.concat([fake_df, real_df], ignore_index=True)

print("Combined Shape:", df.shape)

print(df["target"].value_counts())

Combined Shape: (10206, 2)
target
0    5294
1    4912
Name: count, dtype: int64

# Remove Missing Values

In [16]:
df.dropna(inplace=True)

print(df.shape)

print(df["target"].value_counts())

(10130, 2)
target
0    5268
1    4862
Name: count, dtype: int64

# Text Cleaning Function

In [18]:
ps = PorterStemmer()

def clean_text(text):

    text = str(text)

    text = re.sub('[^a-zA-Z]', ' ', text)

    text = text.lower()

    words = text.split()

    words = [
        ps.stem(word)
        for word in words
        if word not in stopwords.words('english')
    ]

    return " ".join(words)

# Apply Cleaning

In [20]:
df["cleaned_text"] = df["text"].apply(clean_text)

df.head()

,text,target,cleaned_text
0,Russian presidential spokesman Dmitry Peskov r...,1,russian presidenti spokesman dmitri peskov rev...
1,Ahmed Omar Khaled NajehUkrainian Foreign Minis...,1,ahm omar khale najehukrainian foreign minist d...
2,"The Jordanian Seismological Observatory, Ghass...",1,jordanian seismolog observatori ghassan sweida...
3,Ahmed Omar Khaled NajehThe Russian Deputy Fore...,1,ahm omar khale najehth russian deputi foreign ...
4,Ahmed Omar Khaled Nageh The Russian presidenti...,1,ahm omar khale nageh russian presidenti spokes...

# Features and Labels

In [33]:
X = df["cleaned_text"]
y = df["target"]

print(y.unique())
print(y.value_counts())

[1 0]
target
0    5268
1    4862
Name: count, dtype: int64

# TF-IDF Vectorization

In [36]:
vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(X)

print(X.shape)

(10130, 5000)

# Train-Test Split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(y_train.value_counts())
print(y_test.value_counts())

target
0    4214
1    3890
Name: count, dtype: int64
target
0    1054
1     972
Name: count, dtype: int64

# Train Model

In [42]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Trained Successfully")

Model Trained Successfully

# Prediction

In [45]:
y_pred = model.predict(X_test)

# Accuracy

In [48]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9595261599210266

# Classification Report

In [51]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      1054
           1       0.97      0.94      0.96       972

    accuracy                           0.96      2026
   macro avg       0.96      0.96      0.96      2026
weighted avg       0.96      0.96      0.96      2026

# Save Model

In [54]:
joblib.dump(model, "fake_news_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("Model Saved Successfully")

Model Saved Successfully

# Load saved model

In [58]:
import joblib

model = joblib.load("fake_news_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# Live prediction

In [62]:
news = input("Enter News Text: ")

news_vector = vectorizer.transform([news])

prediction = model.predict(news_vector)

if prediction[0] == 1:
    print("Fake News")
else:
    print("Real News")

Enter News Text:  "Western media is becoming unhinged as its anti-Russia propaganda struggles to keep a hold on its consumers. Two recent examples provide evidence.Pro-peace conspiracy emanating from MoscowOn August 28, the New York Times published an article by its Moscow bureau chief about the troubling news (from the Times‘ viewpoint) that the people of Sweden are not happy with their government’s wish to join up with the NATO military alliance.The ruling elites in Sweden and Finland have been quietly pushing for NATO membership for years. In May, the Swedish government pushed through the Riksdag a proposal for a ‘cooperation agreement’ with NATO, allowing it freer access to Swedish territory for transit and training. Finland already has such an agreement in place. In July, government leaders of the two countries proudly joined the NATO summit dinner in Warsaw.But as a Reuters report at the time of the Warsaw summit explained, “An SvD/SIFO opinion poll showed 49 per cent of Swedes opposed joining NATO, with 33 in favor. Most Finns are against entering, and a government report said in April any such move would trigger a crisis with Russia.”A Swedish news outlet reported on the same poll results:“In the survey of 1000 Swedes carried out by pollsters SIFO for newspaper Svenska Dagbladet in June, 49 per cent said they did not want Sweden to join NATO, 33 per cent said yes, and 18 said they were undecided.“The results suggest public opinion has changed since the last SIFO survey on the topic in September of 2015. In that poll, 41 per cent said they were in favour of Sweden seeking NATO membership, 39 per cent said they were against, and 20 per cent were undecided.“At the time, the 2015 figures appeared to demonstrate a significant shift in public opinion in the traditionally non-aligned Nordic country, but SIFO’s most-recent round of results indicates that shift was short-lived.”The Times article by Neil MacFarquharaug began, “With a vigorous national debate underway on whether Sweden should enter a military partnership with NATO, officials in Stockholm suddenly encountered an unsettling problem: a flood of distorted and outright false information on social media, confusing public perceptions of the issue.”The source of the “confusion”? The Times headline reads, ‘A powerful Russian weapon: The spread of false stories’. The article says there is “a flood of distorted and outright false information on social media, confusing public perceptions of the issue.”The Times writer declares a case of Russian dezinformatsiya in action. So powerful is the dezinformatsiya that it can seemingly bamboozle two of the wealthiest and most-educated populations in the world and make them act against their best interests, or at least the best advice of the New York Times, that being to join NATO.As to the exact source of the public tripwire that Swedish government leaders have encountered, the dezinformatsiya conspiracy fades into the mists of the northern boreal forest. The Times explains, “As often happens in such cases, Swedish officials were never able to pin down the source of the false reports. But they, numerous analysts, and experts in American and European intelligence point to Russia as the prime suspect…”Could public attitudes in Finland and Sweden towards NATO have anything to do with the historic ambivalence of Swedes and Finns to imperialist war alliances and their preference for peace over war? Apparently, the New York Times can’t climb out of its Russia conspiracy rut long enough to investigate.According to the Global Peace Index as well as the Global Peace Index (produced annually by the Institute for Economics and Peace), Finland and Sweden score in the top 15 countries of the world in various measures of being peaceful, non-violent places to live. Could it be that the people in Sweden and Finland would like to keep things that way?Meanwhile, here is the New York Times article’s own dezinformatsiya, in the form of a long list of alleged Russian propaganda initiatives that prove what a dastardly enemy it is:* “Disinformation most famously succeeded in early 2014 with the initial obfuscation about deploying Russian forces to seize Crimea.”* “… the simple truth that poorly trained insurgents had accidentally downed the [Malaysian Airlines Flight 17] plane with a missile supplied by Russia.”* “… the Kremlin’s English-language news outlets heavily favored the campaign for [Britain] to leave the European Union, despite their claims of objectivity.”* “Moscow’s targeting of the West with disinformation dates to a Cold War program the Soviets called ‘active measures’.”* “[The Russian state-owned television channel] RT often seems obsessed with the United States, portraying life there as hellish.”*  “The weaponization of information is not some project devised by a Kremlin policy expert but is an integral part of Russian military doctrine…”Reuters can’t write a truthful articleMeanwhile, the Reuters news agency published a report, also on August 28, purporting to look at the prospects for peace in Ukraine. The article is headlined, ‘Germany, Poland and France call for more efforts to end Ukraine crisis‘. Only ten brief paragraphs long, hardly a one in the article is untouched by distortions aimed at casting the best possible light on the right-wing, ultranationalist government in Kyiv and its civil war in the east of the country. Let’s read the ten paragraphs from start to finish:The foreign ministers of Germany, France and Poland agreed on Sunday there should be greater international efforts to end the fighting in eastern Ukraine, German Foreign Minister Frank-Walter Steinmeier told reporters.He said there had not been sufficient progress in implementing the Minsk ceasefire agreement. Western officials were talking with Russia and Ukraine to encourage them to implement measures already agreed in the Minsk process, including communal elections, he said.“Fighting in eastern Ukraine” is Western news-speak for “We don’t’ wish to name the protagonist in the conflict in eastern Ukraine because it happens to be our friend and ally. And what’s more, we are hoping that you don’t notice that it is the army of Ukraine that has invaded and occupied parts of Donbass in eastern Ukraine, not the other way around.”Reuters cites Germany’s foreign minister in saying “Russia and Ukraine” should implement the Minsk-2 ceasefire agreement (signed on February 12, 2015 in the Belarus capital of Minsk). But Minsk-2 is an agreement to end a conflict between two parties in Ukraine–the governing regime in Kyiv, and the people’s republics in Donbass (Donetsk and Lugansk). The agreement spells out the precise measures to be taken on both sides, including a cessation of military hostilities, comprehensive prisoner exchanges, recognition by Kyiv of autonomy for Donetsk and Lugansk, to be followed by the holding of elections there, and so on. What does all this have to do with Russia, apart from the obvious facilitation role which Russia (and other regional powers) could fulfill? Is Russia supposed to take over Ukraine so that Minsk-2 may be implemented? How well would that go over in Berlin and Washington?Why not “Germany and Ukraine” or “France and Ukraine” to be encouraged to implement Minsk? After all, Germany and France are among the four members of the ‘Normandy Four’ group constituted to facilitate a resolution of the crisis in Ukraine and under whose facilitation Minsk-2 was arrived at in the first place.“We have to work for a de-escalation of the situation,” [Steinmeier] told reporters after a meeting with his counterparts aimed at reinvigorating the Weimar Triangle [Germany-France-Poland] trilateral group.Steinmeier said the group also wanted to reassure Europeans about the continued importance and relevance of the European Union after the June 23 vote by Britain to exit the bloc.“The Weimar Triangle can plan an important role … It is a format where we can discuss progress or the lack of progress on issues such as the Normandy format aimed at ending the Ukraine conflict,” Steinmeier said.The Normandy group comprises Russia, Ukraine, France and Germany.So what, exactly, have Germany and France been doing to “de-escalate” the conflict in Ukraine? Have they called on Ukraine to pull its heavy weaponry out of the ceasefire zone and cease its criminal, daily shellings of towns and cities in Donbass, in total violation of Minsk-2? No. Have they called out Ukraine for refusing to recognize the Donetsk and Lugansk republics and thereby blocking the holding of elections as required by Minsk-2? No. How about Ukraine’s failure to conduct prisoner exchanges; have Germany and France scolded Ukraine for that? No. So why is Reuters misleading its readers about Germany and France’s failure to work to “de-escalate” the conflict?The misleading is even worse, because not only have Germany and France failed to aid in de-escalating the conflict, they are constantly adding fuel to the fire. Recently, they led the European Union in extending EU economic sanctions against Russia, including Crimea. They are silent about the provocative action of the United States, Britain and Canada in providing military training and equipping of the Ukrainian army and paramilitary irregulars, which is then applied to the illegal and criminal war against the citizens of Donbass.Germany and France are members of the NATO alliance whose lead member, the United States, recently constructed provocative and dangerous missile bases in Romania and Poland. These bases have been built as the U.S. undertakes a massive, trillion dollars-plus upgrade of its nuclear weapons. This includes designing new delivery systems that undo the current status quo of nuclear stand-off and greatly increase the possibility of accidental unleashing of nuclear weapons.Why can’t Reuters provide its readers with important background information of the conflict in Ukraine instead of printing bland phrases that convey exactly the opposite impression of what is really taking place?The leaders of Russia, Germany and France have agreed to meet to discuss the situation in Ukraine on Sept. 4-5 in China on the sidelines of the G20 summit, the Kremlin said last week.A recent surge in fighting in eastern Ukraine, where Kiev is fighting pro-Russian separatists, and fresh tension in Crimea have raised concern that a fragile ceasefire agreed in Minsk in February 2015 could collapse.“Recent surge in fighting in eastern Ukraine” is Reuters-speak for that which not must be spoken: in recent months, Ukraine has greatly increased its criminal shellings of the people of Donbass. What’s more, Ukraine conducts an ongoing military occupation of Donetsk and Lugansk territory and it calls the self-defense forces of Donbass “terrorists”, thus showing it has absolutely no intention of reaching a political settlement.Ukrainian President Petro Poroshenko said last week he did not rule out introducing martial law and a new wave of military mobilization if the separatist conflict worsened.“Separatist conflict” is Kyiv-speak/Reuters-speak for obscuring and confusing the source of the conflict in eastern Ukraine, which is the refusal of Kyiv to grant the slightest decentralization of power in the highly-centralized Ukrainian constitutional setup whereby regions of Donbass could achieve a desired autonomy.Of course, as a result of Ukraine’s prolonged and cruel war against the people of Donbass, it is highly likely that if given the chance, they would vote to secede from Ukraine to either join Russia or constitute their own independent republics. But that hardly makes them criminals or “terrorists. As a matter of fact, that would be an entirely lawful act, consistent with international law, such as it is, and consistent with recent political experience in such countries as Canada (Quebec) and the United Kingdom (Scotland).Propaganda disguised as news or policy is the modus operandi of Western media outlets in reporting on Ukraine. It’s a major contributor to making the conflict there so intractable because it lessens the pressure that would otherwise operate on the ultra-nationalist regime in Kyiv that it cease its civil war course. Roger Annis is a retired aerospace worker in Vancouver BC. He writes regularly for Counterpunch and compiles his writings on a ‘A Socialist in Canada’. He is an editor of the website The New Cold War: Ukraine and beyond. He can be reached at rogerannis@hotmail.com. "

Fake News